/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testfinalproject;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author raysen
 */
public class A3AddNewCashTransaction extends javax.swing.JFrame {
    Connection con = db.mycon();
    ResultSet rs = null;
    PreparedStatement pst = null;
    String email;
    Statement stmt = null;
    int userID;
    /**
     * Creates new form Login
     */
    public A3AddNewCashTransaction() {
        initComponents();
        this.setLocation(770, 25);
        time();
        con = db.mycon();
        scaleImage(jIcon, "/pictures/Screenshot_20221218_101736.png");
        scaleImage(jLogo, "/pictures/E-Montra Logo.png");
        scaleImage(jBackButton, "/pictures/Screenshot_20230105_115732.png");
        
        ButtonGroup expenseOrIncome = new ButtonGroup();
        expenseOrIncome.add(jExpenseRadioButton);
        expenseOrIncome.add(jIncomeRadioButton);
    }
    
    A3AddNewCashTransaction(int userIDParameter) {
        
        this();
        userID = userIDParameter;
        //email = em;
//        showingTransaction(userID);
    }
    
    public void time(){
        Timer timer;
        
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                
                java.util.Date date = new java.util.Date();
                SimpleDateFormat st = new SimpleDateFormat("hh:mm");
                
                String clockString = st.format(date);
                
                jClock.setText(clockString);
            }   
        });
        
        timer.start();
    }
    
    
    
    public void scaleImage(JLabel address,String imgURL) {
        ImageIcon icon = new ImageIcon(getClass().getResource(imgURL));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(address.getWidth(), address.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        address.setIcon(scaledIcon );
        address.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jAmount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jClock = new javax.swing.JLabel();
        jIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescription = new javax.swing.JTextArea();
        jExpenseRadioButton = new javax.swing.JRadioButton();
        jIncomeRadioButton = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jBackButton = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 255, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(Cash)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 240, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Amount : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountActionPerformed(evt);
            }
        });
        jAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAmountKeyTyped(evt);
            }
        });
        jPanel1.add(jAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 300, -1));

        jButton1.setBackground(new java.awt.Color(64, 128, 128));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add New Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 360, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Transaction Type : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Date : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jPanel2.setBackground(new java.awt.Color(241, 255, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jClock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jClock.setText("hh:mm");
        jPanel2.add(jClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jIcon.setText("icon (wifi, etc)");
        jIcon.setPreferredSize(new java.awt.Dimension(67, 12));
        jPanel2.add(jIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 15, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add New Transaction");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 210, 250, -1));

        jLogo.setText("                                  Logo");
        jLogo.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel1.add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Description : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jDescription.setColumns(20);
        jDescription.setRows(5);
        jScrollPane1.setViewportView(jDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 300, -1));

        jExpenseRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jExpenseRadioButton.setText("Expense");
        jExpenseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExpenseRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jExpenseRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        jIncomeRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jIncomeRadioButton.setText("Income");
        jIncomeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncomeRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jIncomeRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, 30));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 190, 30));

        jBackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBackButton.setText("Back");
        jBackButton.setToolTipText("");
        jBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Register code here

        String amount = jAmount.getText();
        String transactionType;
        if(jExpenseRadioButton.isSelected()){
            transactionType = "Expense";
        }else if(jIncomeRadioButton.isSelected()){
            transactionType = "Income";
        }
        String date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();

        int balance;

        if(jExpenseRadioButton.isSelected()){
            try {

                String sql = "SELECT * FROM accounts WHERE eMoneyID=? && userID=?";
                pst = con.prepareCall(sql);

                pst.setString(1, "CASHID_R01"); // pin
                pst.setString(2, String.valueOf(userID));

                rs = pst.executeQuery();



                if (rs.next()) { // if there is still a table next to the table, then true
                    String sqlForPay = "UPDATE accounts " +
                             "SET eMoneyBalance = eMoneyBalance - " + amount +
                             " WHERE eMoneyID = 'CASHID_R01' AND userID = " + userID +";";

                    Statement s = db.mycon().createStatement();

                    s.executeUpdate(sqlForPay);

                    String sqlForInsertNewTransaction = " INSERT INTO transactionhistory (transactionType, amount, transactionDate, userID) " +
                                                        "VALUES ('Expense','"+amount+"','"+date+"','"+userID+"')";

                    s.executeUpdate(sqlForInsertNewTransaction);

                    JOptionPane.showMessageDialog(rootPane, "Adding New Transaction Successful!");

    //                this.setVisible(false);
    //                new OA1GopayPayment().setVisible(true);
                    
                    jAmount.setText("");
                    jExpenseRadioButton.doClick();
                    jDescription.setText("");
                } else { // its false DO this
                    JOptionPane.showMessageDialog(rootPane, "Choose Transaction Type!");
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        } else if(jIncomeRadioButton.isSelected()){
            try {

                String sql = "SELECT * FROM accounts WHERE eMoneyID=? && userID=?";
                pst = con.prepareCall(sql);

                pst.setString(1, "CASHID_R01"); // pin
                pst.setString(2, String.valueOf(userID));

                rs = pst.executeQuery();



                if (rs.next() && jIncomeRadioButton.isSelected()) { // if there is still a table next to the table, then true
                    String sqlForPay = "UPDATE accounts " +
                             "SET eMoneyBalance = eMoneyBalance + " + amount +
                             " WHERE eMoneyID = 'CASHID_R01' AND userID = " + userID +";";

                    Statement s = db.mycon().createStatement();

                    s.executeUpdate(sqlForPay);

                    String sqlForInsertNewTransaction = " INSERT INTO transactionhistory (transactionType, amount, transactionDate, userID) " +
                                                        "VALUES ('Income','"+amount+"','"+date+"','"+userID+"')";

                    s.executeUpdate(sqlForInsertNewTransaction);

                    JOptionPane.showMessageDialog(rootPane, "Adding New Transaction Successful!");

//                    this.setVisible(false);
//                    new OA1GopayPayment().setVisible(true);
                    
                    jAmount.setText("");
                    jIncomeRadioButton.doClick();
                    jDescription.setText("");
                } else { // its false DO this
                    JOptionPane.showMessageDialog(rootPane, "Choose Transaction Type!");
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        }
//        
//        try {
//            
//            String sql = "SELECT * FROM gopayaccount WHERE pinNumber=?";
//            pst = con.prepareCall(sql);
//            
//            pst.setString(1, pin); // pin
//            
//            rs = pst.executeQuery();
//            
//            if (rs.next()) { // if there is still a table next to the table, then true
//                
//                
//                balance = rs.getInt("eMoneyBalance");
//                
////                System.out.println(balance);
//                
//                String sqlToConnectBalance = "UPDATE accounts " +
//                         "SET eMoneyBalance = " + balance +
//                         " WHERE eMoneyID = 'GPAYID_R01';";
//                
//                Statement s = db.mycon().createStatement();
//                
//                s.executeUpdate(sqlToConnectBalance);
//                    
//                JOptionPane.showMessageDialog(rootPane, "Payment Successful");
//
////                this.setVisible(false);
////                new OA1GopayPayment().setVisible(true);
//                jItem.setText("");
//                jPrice.setText("");
//                jPin.setText("");
//            } else { // its false DO this
////                JOptionPane.showMessageDialog(rootPane, "Payment failed! Check Your PIN");
//            }
//            
//        } catch (Exception e) {
//            System.out.println(e);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jExpenseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExpenseRadioButtonActionPerformed
//        if(jIncomeRadioButton.isSelected()){
//           jIncomeRadioButton.doClick();
//        }
    }//GEN-LAST:event_jExpenseRadioButtonActionPerformed

    private void jIncomeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncomeRadioButtonActionPerformed
//        if(jExpenseRadioButton.isSelected()){
//           jExpenseRadioButton.doClick();
//        }
    }//GEN-LAST:event_jIncomeRadioButtonActionPerformed

    private void jAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAmountKeyTyped
        char c = evt.getKeyChar();
         
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jAmountKeyTyped

    private void jBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackButtonMouseClicked
        this.setVisible(false);
        new A1Home(userID).setVisible(true);
    }//GEN-LAST:event_jBackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3AddNewCashTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3AddNewCashTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3AddNewCashTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3AddNewCashTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3AddNewCashTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAmount;
    private javax.swing.JLabel jBackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jClock;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JTextArea jDescription;
    private javax.swing.JRadioButton jExpenseRadioButton;
    private javax.swing.JLabel jIcon;
    private javax.swing.JRadioButton jIncomeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
